### ISSUE TITLE
为什么你的博客没有启用评论功能呢？

### ISSUE THREAD

**Issue by geekrainy** [cfanlife/cfanlife.github.io#1]
RT，想发表评论都不可以。是使用jekyll搭建的吗？

**Comment by cfanlife** [comment]
不好意思，暂未加入评论功能，是使用jekyll搭建的

**Comment by cfanlife** [comment]
不好意思，暂未加入评论功能，是使用jekyll搭建的

**Comment by geekrainy** [comment]
呃，搜KMUST发现你的。

**Comment by cfanlife** [comment]
@geekrainy 当时是自己做了个小东西，就传到这里来了，起的名字跟KMUST相关
